import { afterAll, beforeAll, expect, it } from 'vitest';
import { PGlite } from '@electric-sql/pglite';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';

const environment = 'hclab-equipments-d0ehkkk05991a35';
const admin = 'cloudbase-admin-sub',
  student = 'cloudbase-student-sub',
  other = 'cloudbase-other-sub';
let db: PGlite;
let equipment: string, booking: string;
let legacyReservation: { uid: string; username: string; completed: boolean };
const legacyEmail = 'legacy-username@test.edu';
const legacyToken = '48ae1452-313b-461e-b9f5-9e4f11d2b8ca';

async function identity(sub = 'anon', databaseRole = 'anon', jwtRole = databaseRole) {
  await db.exec('reset role');
  await db.query("select set_config('request.jwt.claims',$1,false)", [
    JSON.stringify({ sub, role: jwtRole }),
  ]);
  await db.exec(`set role ${databaseRole}`);
}
async function call(name: string, args: unknown[] = []) {
  return (
    await db.query<{ value: any }>(
      `select ${name}(${args.map((_, i) => '$' + (i + 1)).join(',')}) as value`,
      args,
    )
  ).rows[0].value;
}
function registration(email: string, token: string) {
  return {
    email,
    token,
    username:
      'hclab_' + createHash('sha256').update(email.trim().toLowerCase()).digest('hex').slice(0, 40),
    name: '新同学',
    student_id: 'NEW-001',
    project: '机器人实验',
    role: 'admin',
  };
}
async function examResult(email: string, score = 100) {
  await identity();
  const exam = await call('public.start_exam', [email]);
  expect(exam.questions).toHaveLength(10);
  expect(
    exam.questions.every((q: any) => q.answer === undefined && q.explanation === undefined),
  ).toBe(true);
  await identity('anon', 'postgres');
  const key = (
    await db.query<{ id: number; answer: number }>('select id, answer from private.questions')
  ).rows;
  const answers = Object.fromEntries(
    exam.questions.map((q: any, i: number) => {
      const answer = key.find((a) => a.id === q.id)!.answer;
      return [q.id, i < score / 10 ? answer : (answer + 1) % 4];
    }),
  );
  await identity();
  const result = await call('public.submit_exam', [exam.id, answers]);
  await expect(call('public.submit_exam', [exam.id, answers])).rejects.toThrow(/已提交|超时/);
  await identity('anon', 'postgres');
  return { ...result, examId: exam.id };
}
async function nativeAccount(uid: string, username: string, project = environment) {
  await db.query('insert into auth.users(sub, username, project) values($1,$2,$3)', [
    uid,
    username,
    project,
  ]);
}

beforeAll(async () => {
  db = new PGlite();
  // Matches the verified CloudBase identity columns, including text JWT sub and literal anon.
  await db.exec(`
    create role anon; create role authenticated;
    create schema auth;
    create table auth.users(id bigint generated by default as identity primary key, project varchar(64) not null, sub varchar(255) not null, username varchar(64), email varchar(512), unique(project,sub), unique(project,username));
    create function auth.jwt() returns jsonb language sql stable as $$ select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb $$;
    create function auth.uid() returns text language sql stable as $$ select auth.jwt()->>'sub' $$;
    grant usage on schema auth to anon,authenticated;
    grant execute on function auth.jwt(),auth.uid() to anon,authenticated;
    create schema storage;
    create table storage.buckets(id text primary key,name text not null,public boolean default false,file_size_limit bigint,allowed_mime_types text[],owner_id text);
    create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text references storage.buckets(id),name text,owner_id text);
    alter table storage.objects enable row level security;
    grant usage on schema storage to anon,authenticated;
    grant select,insert,update,delete on storage.objects to anon,authenticated;
  `);
  await db.exec(readFileSync('cloudbase/migrations/20260914000000_platform.sql', 'utf8'));
  // Simulate the existing account/reservation that predates the sign-in limit fix.
  await db.query(
    "insert into private.exam_attempts(email,questions,completed,score,token) values($1,'[]',true,100,$2)",
    [legacyEmail, legacyToken],
  );
  legacyReservation = await call('private.claim_registration', [
    {
      ...registration(legacyEmail, legacyToken),
      username: 'hclab_' + createHash('sha256').update(legacyEmail).digest('hex').slice(0, 48),
    },
  ]);
  await nativeAccount(legacyReservation.uid, legacyReservation.username);
  await db.exec(readFileSync('cloudbase/migrations/20260914000001_username_length.sql', 'utf8'));
  await db.exec(readFileSync('cloudbase/migrations/20260914000002_rpc_results.sql', 'utf8'));
}, 20000);
afterAll(async () => {
  await db?.close();
});

it('bootstraps CloudBase in one migration with an answer bank and no demo accounts or equipment', async () => {
  expect(
    (await db.query<{ name: string | null }>("select to_regclass('public.profiles')::text as name"))
      .rows[0].name,
  ).toBe('profiles');
  expect((await db.query('select * from public.profiles')).rows).toEqual([]);
  expect((await db.query('select * from public.equipment')).rows).toEqual([]);
  expect((await db.query('select * from private.questions')).rows).toHaveLength(30);
  const bucket = (
    await db.query<{ public: boolean; file_size_limit: number; allowed_mime_types: string[] }>(
      "select * from storage.buckets where id='equipment-images'",
    )
  ).rows[0];
  expect(bucket.public).toBe(true);
  expect(Number(bucket.file_size_limit)).toBe(2097152);
  expect(bucket.allowed_mime_types).toEqual(['image/jpeg', 'image/png', 'image/webp']);
});

it.each([80, 90])('%i points cannot issue or redeem an admission token', async (score) => {
  const email = `score-${score}@test.edu`;
  const result = await examResult(email, score);
  expect(result).toMatchObject({ score, passed: false, token: null });
  const token = (
    await db.query<{ token: string }>(
      'update private.exam_attempts set token=gen_random_uuid() where id=$1 returning token',
      [result.examId],
    )
  ).rows[0].token;
  await expect(call('private.claim_registration', [registration(email, token)])).rejects.toThrow(
    /考试|凭证/,
  );
});

it('new registration usernames fit the native sign-in limit of 48 characters', async () => {
  const email = 'username-limit@test.edu';
  const result = await examResult(email);
  const data = registration(email, result.token);
  const hash = createHash('sha256').update(email).digest('hex');
  await expect(
    call('private.claim_registration', [{ ...data, username: 'hclab_' + hash.slice(0, 48) }]),
  ).rejects.toThrow(/账号标识/);
  const claimed = await call('private.claim_registration', [
    { ...data, username: 'hclab_' + hash.slice(0, 40) },
  ]);
  expect(claimed.username).toHaveLength(46);
});

it('the username migration preserves legacy reservations and never renames native accounts', async () => {
  await identity('anon', 'postgres');
  const reservation = (
    await db.query(
      'select uid,username,completed from private.registration_intents where token=$1',
      [legacyToken],
    )
  ).rows[0];
  expect(reservation).toEqual(legacyReservation);
  expect(
    (await db.query('select username from auth.users where sub=$1', [legacyReservation.uid]))
      .rows[0],
  ).toEqual({ username: legacyReservation.username });
  expect(legacyReservation.username).toHaveLength(54);
  await expect(
    call('private.claim_registration', [
      { ...registration(legacyEmail, legacyToken), username: legacyReservation.username },
    ]),
  ).rejects.toThrow(/账号标识/);
});

it('100 points binds one native identity, accepts exact retries, and always creates a regular user', async () => {
  const result = await examResult('new@test.edu');
  expect(result).toMatchObject({ score: 100, passed: true });
  const data = registration('new@test.edu', result.token);
  await expect(
    call('private.claim_registration', [{ ...data, email: 'other-email@test.edu' }]),
  ).rejects.toThrow(/邮箱|凭证/);
  const claim = await call('private.claim_registration', [{ ...data, email: ' NEW@test.edu ' }]);
  expect(claim.uid).toMatch(/^[0-9a-f-]{36}$/);
  expect(claim).toMatchObject({ username: data.username, completed: false });
  expect(await call('private.claim_registration', [data])).toEqual(claim);
  for (const changed of [
    { name: '另一人' },
    { student_id: 'DIFFERENT' },
    { project: '另一个项目' },
    { username: 'hclab_' + 'a'.repeat(40) },
  ]) {
    await expect(call('private.claim_registration', [{ ...data, ...changed }])).rejects.toThrow(
      /绑定|一致|凭证/,
    );
  }
  await expect(call('private.finish_registration', [result.token])).rejects.toThrow(/原生|账号/);
  await nativeAccount(claim.uid, claim.username, 'wrong-environment');
  await expect(call('private.finish_registration', [result.token])).rejects.toThrow(/原生|账号/);
  await db.query('update auth.users set project=$1 where sub=$2', [environment, claim.uid]);
  const finished = await call('private.finish_registration', [result.token]);
  expect(finished).toEqual({ ...claim, completed: true });
  expect(await call('private.finish_registration', [result.token])).toEqual(finished);
  expect(await call('private.claim_registration', [data])).toEqual(finished);
  const profile = (await db.query('select * from public.profiles where id=$1', [claim.uid]))
    .rows[0];
  expect(profile).toMatchObject({
    email: 'new@test.edu',
    role: 'user',
    rules_version: '2026-09-v2',
    student_id: 'NEW-001',
    project: '机器人实验',
  });
  expect(
    (await db.query('select * from public.notices where user_id=$1', [claim.uid])).rows,
  ).toHaveLength(1);
  expect(
    (
      await db.query<{ consumed: boolean }>(
        'select consumed from private.exam_attempts where token=$1',
        [result.token],
      )
    ).rows[0].consumed,
  ).toBe(true);
  // Completed retries remain idempotent even after the original proof expires.
  await db.query(
    "update private.exam_attempts set expires_at=now()-interval '1 day' where token=$1",
    [result.token],
  );
  expect(await call('private.claim_registration', [data])).toEqual(finished);
  await expect(call('private.claim_registration', [{ ...data, name: '替换身份' }])).rejects.toThrow(
    /绑定|一致|凭证/,
  );
  const second = await examResult('new@test.edu');
  await expect(
    call('private.claim_registration', [registration('new@test.edu', second.token)]),
  ).rejects.toThrow(/已注册|绑定|账号/);
});

it.each([
  ['expired', "expires_at=now()-interval '1 second'"],
  ['old rules', "rules_version='2026-09-v1'"],
  ['incomplete', 'completed=false'],
  ['consumed', 'consumed=true'],
])('rejects %s exam proofs at the trusted registration boundary', async (label, mutation) => {
  const email = label.replaceAll(' ', '-') + '@test.edu';
  const result = await examResult(email);
  await db.query(`update private.exam_attempts set ${mutation} where token=$1`, [result.token]);
  await expect(
    call('private.claim_registration', [registration(email, result.token)]),
  ).rejects.toThrow(/考试|凭证/);
});

it('validates registration fields and refuses existing native accounts or a mismatched UID', async () => {
  const result = await examResult('validation@test.edu');
  const data = registration('validation@test.edu', result.token);
  for (const changed of [
    { name: ' ' },
    { student_id: '' },
    { project: '' },
    { project: 'x'.repeat(121) },
    { username: 'plain-user' },
  ]) {
    await expect(call('private.claim_registration', [{ ...data, ...changed }])).rejects.toThrow();
  }
  const claim = await call('private.claim_registration', [data]);
  await nativeAccount('an-unrelated-sub', claim.username);
  await expect(call('private.finish_registration', [result.token])).rejects.toThrow(/原生|账号/);
  await expect(call('private.claim_registration', [data])).rejects.toThrow(/原生|账号|绑定/);
  expect(
    (await db.query('select * from public.profiles where email=$1', [data.email])).rows,
  ).toEqual([]);
});

it.each([false, true])(
  'a fresh full-score proof resumes an expired reservation with the same identity (native account exists: %s)',
  async (created) => {
    const email = `resume-${created}@test.edu`;
    const original = await examResult(email);
    const oldData = registration(email, original.token);
    const reserved = await call('private.claim_registration', [oldData]);
    if (created) await nativeAccount(reserved.uid, reserved.username);
    await db.query(
      "update private.exam_attempts set expires_at=now()-interval '1 hour' where token=$1",
      [original.token],
    );
    await expect(call('private.claim_registration', [oldData])).rejects.toThrow(/过期/);
    const renewal = await examResult(email);
    const newData = registration(email, renewal.token);
    await expect(
      call('private.claim_registration', [{ ...newData, student_id: 'IMPOSTOR' }]),
    ).rejects.toThrow(/绑定|一致/);
    expect(await call('private.claim_registration', [newData])).toEqual(reserved);
    await expect(call('private.claim_registration', [oldData])).rejects.toThrow(/已使用|凭证/);
    await expect(call('private.finish_registration', [original.token])).rejects.toThrow(
      /凭证|绑定/,
    );
    if (!created) await nativeAccount(reserved.uid, reserved.username);
    expect(await call('private.finish_registration', [renewal.token])).toEqual({
      ...reserved,
      completed: true,
    });
    expect(
      (await db.query('select * from public.profiles where email=$1', [email])).rows,
    ).toHaveLength(1);
    expect(
      (
        await db.query('select * from auth.users where project=$1 and username=$2', [
          environment,
          reserved.username,
        ])
      ).rows,
    ).toHaveLength(1);
  },
);

it('old completed registration proofs do not block exam cleanup or lose their retry identity', async () => {
  await identity('anon', 'postgres');
  const saved = (
    await db.query<{ token: string }>(
      "select token from private.registration_intents where email='new@test.edu'",
    )
  ).rows[0];
  await db.query(
    "update private.exam_attempts set created_at=now()-interval '8 days' where token=$1",
    [saved.token],
  );
  const result = await examResult('after-cleanup@test.edu');
  expect(result.passed).toBe(true);
  expect(
    await call('private.claim_registration', [registration('new@test.edu', saved.token)]),
  ).toMatchObject({ completed: true });
});

it('native account creation alone cannot create a platform profile or reveal authenticated data', async () => {
  await identity('anon', 'postgres');
  await nativeAccount('native-without-exam', 'native-without-exam');
  expect(
    (await db.query("select * from public.profiles where id='native-without-exam'")).rows,
  ).toEqual([]);
  await identity('native-without-exam', 'authenticated');
  const snapshot = await call('public.get_snapshot');
  for (const key of ['profiles', 'bookings', 'notices', 'violations', 'busy'])
    expect(snapshot[key]).toEqual([]);
  await expect(call('public.mark_notices_read')).rejects.toThrow(/登录/);
});

it('regular users cannot call registration internals, read answers, change roles, or write tables directly', async () => {
  await identity('anon', 'postgres');
  for (const [sub, name, role] of [
    [admin, '管理员', 'admin'],
    [student, '同学甲', 'user'],
    [other, '同学乙', 'user'],
  ]) {
    await nativeAccount(sub, sub);
    await db.query(
      'insert into public.profiles(id,email,name,student_id,project,role) values($1,$2,$3,$1,$3,$4)',
      [sub, `${sub}@test.edu`, name, role],
    );
  }
  for (const [sub, role] of [
    ['anon', 'anon'],
    [student, 'authenticated'],
    [admin, 'authenticated'],
  ]) {
    await identity(sub, role);
    await expect(call('private.claim_registration', [{}])).rejects.toThrow(/permission denied/);
    await expect(
      call('private.finish_registration', ['00000000-0000-0000-0000-000000000000']),
    ).rejects.toThrow(/permission denied/);
    await expect(db.exec('select * from private.questions')).rejects.toThrow(/permission denied/);
    await expect(db.exec('select * from private.registration_intents')).rejects.toThrow(
      /permission denied/,
    );
    await expect(db.exec("update public.profiles set role='admin'")).rejects.toThrow(
      /permission denied/,
    );
    await expect(db.exec('insert into public.bookings default values')).rejects.toThrow(
      /permission denied/,
    );
  }
  await identity(student, 'authenticated');
  await expect(call('public.save_equipment', [{}])).rejects.toThrow(/管理员/);
  await expect(call('public.record_violation', [other, '伪造违规'])).rejects.toThrow(/管理员/);
});

it('admins save real equipment and storage policies deny ordinary uploads', async () => {
  await identity(admin, 'authenticated');
  const data = {
    name: '测试机械臂',
    model: 'FR3',
    category: '机械臂',
    project: '机器人',
    room: '504',
    location: '绿色工作台',
    manager_id: admin,
    status: 'available',
    weekdays: [0, 1, 2, 3, 4, 5, 6],
    open_time: '08:00',
    close_time: '22:00',
    asset_code: 'TEST-CLOUDBASE',
  };
  await expect(call('public.save_equipment', [{ ...data, room: '506' }])).rejects.toThrow();
  equipment = await call('public.save_equipment', [data]);
  expect((await call('public.get_snapshot')).equipment[0]).toMatchObject({
    id: equipment,
    manager_id: admin,
    room: '504',
    location: '绿色工作台',
  });
  await db.query(
    "insert into storage.objects(bucket_id,name,owner_id) values('equipment-images','test.png',$1)",
    [admin],
  );
  await identity(student, 'authenticated');
  await expect(
    db.query(
      "insert into storage.objects(bucket_id,name,owner_id) values('equipment-images','forged.png',$1)",
      [student],
    ),
  ).rejects.toThrow();
  await identity();
  expect((await db.query('select * from storage.objects')).rows).toHaveLength(1);
});

it('booking conflicts are rejected across users and personal records remain isolated', async () => {
  const data = {
    equipment_id: equipment,
    starts_at: '2099-01-02T09:00+08:00',
    ends_at: '2099-01-02T10:00+08:00',
    purpose: '抓取实验',
  };
  await identity(student, 'authenticated');
  booking = await call('public.create_booking', [data]);
  await identity(other, 'authenticated');
  await expect(call('public.create_booking', [data])).rejects.toThrow(/已有预约/);
  const snapshot = await call('public.get_snapshot');
  expect(snapshot.profiles.map((p: any) => p.id)).toEqual([other]);
  expect(snapshot.bookings).toEqual([]);
  expect(snapshot.busy).toHaveLength(1);
  expect(Object.keys(snapshot.busy[0]).sort()).toEqual([
    'ends_at',
    'equipment_id',
    'starts_at',
    'status',
  ]);
  expect((await db.query('select * from public.bookings')).rows).toEqual([]);
  expect((await db.query('select id from public.profiles')).rows).toEqual([{ id: other }]);
  await expect(call('public.booking_action', [booking, 'approve', ''])).rejects.toThrow(/管理员/);
  await expect(call('public.booking_action', [booking, 'cancel', ''])).rejects.toThrow(/申请人/);
});

it('literal anon and a forged subject with the wrong JWT role expose no private records or busy slots', async () => {
  for (const [sub, sqlRole, jwtRole] of [
    ['anon', 'anon', 'anon'],
    [admin, 'authenticated', 'anon'],
    [student, 'authenticated', ''],
    ['no-profile', 'authenticated', 'authenticated'],
  ]) {
    await identity(sub, sqlRole, jwtRole);
    const snapshot = await call('public.get_snapshot');
    expect(snapshot.equipment).toHaveLength(1);
    for (const key of ['profiles', 'bookings', 'notices', 'violations', 'busy'])
      expect(snapshot[key]).toEqual([]);
    await expect(call('public.mark_notices_read')).rejects.toThrow();
    await expect(call('public.create_booking', [{ equipment_id: equipment }])).rejects.toThrow();
    if (sqlRole === 'authenticated') {
      expect(await call('public.is_admin')).toBe(false);
      expect((await db.query('select * from public.profiles')).rows).toEqual([]);
      expect((await db.query('select * from public.bookings')).rows).toEqual([]);
      await expect(call('public.save_equipment', [{}])).rejects.toThrow();
    } else {
      await expect(db.exec('select * from public.profiles')).rejects.toThrow(/permission denied/);
    }
  }
});

it('admin approval and violations notify the owner, with suspended users blocked from booking', async () => {
  await identity(admin, 'authenticated');
  await call('public.booking_action', [booking, 'approve', '请按时归还']);
  await call('public.record_violation', [other, '首次未归位']);
  await call('public.record_violation', [other, '再次未归位']);
  await identity(student, 'authenticated');
  const snapshot = await call('public.get_snapshot');
  expect(snapshot.bookings[0].status).toBe('approved');
  expect(snapshot.notices.some((n: any) => n.title === '预约已批准')).toBe(true);
  await call('public.mark_notices_read');
  expect((await call('public.get_snapshot')).notices.every((n: any) => n.read)).toBe(true);
  await identity(other, 'authenticated');
  expect((await call('public.get_snapshot')).profiles[0].violations_count).toBe(2);
  await expect(
    call('public.create_booking', [
      {
        equipment_id: equipment,
        starts_at: '2099-01-03T09:00+08:00',
        ends_at: '2099-01-03T10:00+08:00',
        purpose: '测试',
      },
    ]),
  ).rejects.toThrow(/准入/);
});

it('object-returning RPCs expose the committed equipment and booking IDs without repeating writes', async () => {
  await identity(admin, 'authenticated');
  const current = (await call('public.get_snapshot')).equipment.find(
    (item: any) => item.id === equipment,
  );
  const saved = await call('public.save_equipment_result', [
    { ...current, name: '更新后的机械臂' },
  ]);
  expect(saved).toEqual({ id: equipment });
  expect(
    (await call('public.get_snapshot')).equipment.find((item: any) => item.id === saved.id).name,
  ).toBe('更新后的机械臂');
  await identity(student, 'authenticated');
  const input = {
    equipment_id: equipment,
    starts_at: '2099-01-04T09:00+08:00',
    ends_at: '2099-01-04T10:00+08:00',
    purpose: 'JSON 返回值预约测试',
  };
  const created = await call('public.create_booking_result', [input]);
  expect(created).toEqual({ id: expect.stringMatching(/^[0-9a-f-]{36}$/) });
  expect(
    (await call('public.get_snapshot')).bookings.find((item: any) => item.id === created.id),
  ).toMatchObject({ user_id: student, equipment_id: equipment, purpose: input.purpose });
  await expect(call('public.create_booking_result', [input])).rejects.toThrow(/已有预约/);
});

it('object-returning wrappers retain authenticated and administrator permission boundaries', async () => {
  for (const [sub, databaseRole, jwtRole] of [
    ['anon', 'anon', 'anon'],
    ['no-profile', 'authenticated', 'authenticated'],
    [admin, 'authenticated', 'anon'],
  ]) {
    await identity(sub, databaseRole, jwtRole);
    for (const fn of ['public.save_equipment_result', 'public.create_booking_result']) {
      await expect(call(fn, [{}])).rejects.toThrow(
        databaseRole === 'anon' ? /permission denied/ : /登录/,
      );
    }
  }
  await identity(student, 'authenticated');
  await expect(call('public.save_equipment_result', [{}])).rejects.toThrow(/管理员/);
});

it('rules v3 preserves admitted members and makes new registrations acknowledge the extracted rules', async () => {
  const old = await examResult('pre-v3@test.edu');
  const before = (await db.query('select id,rules_version from public.profiles order by id')).rows;
  await db.exec(readFileSync('cloudbase/migrations/20260914000003_rules_update.sql', 'utf8'));
  expect((await db.query('select id,rules_version from public.profiles order by id')).rows).toEqual(
    before,
  );
  const legacy = await call('private.claim_registration', [
    registration('pre-v3@test.edu', old.token),
  ]);
  await nativeAccount(legacy.uid, legacy.username);
  await call('private.finish_registration', [old.token]);
  expect(
    (await db.query('select rules_version from public.profiles where id=$1', [legacy.uid])).rows[0],
  ).toEqual({ rules_version: '2026-09-v2' });
  const email = 'rules-v3@test.edu';
  const passed = await examResult(email);
  expect(
    (await db.query('select rules_version from private.exam_attempts where id=$1', [passed.examId]))
      .rows[0],
  ).toEqual({ rules_version: '2026-09-v3' });
  const reserved = await call('private.claim_registration', [registration(email, passed.token)]);
  await nativeAccount(reserved.uid, reserved.username);
  await call('private.finish_registration', [passed.token]);
  expect(
    (await db.query('select role,rules_version from public.profiles where id=$1', [reserved.uid]))
      .rows[0],
  ).toEqual({ role: 'user', rules_version: '2026-09-v3' });
  await identity();
  await expect(
    call('private.claim_registration', [registration(email, passed.token)]),
  ).rejects.toThrow(/permission denied/);
});
