import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { PGlite } from '@electric-sql/pglite';
import { createHash, randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';

const env = 'hclab-equipments-d0ehkkk05991a35';
const owner = '10000000-0000-0000-0000-000000000001';
const admin = '10000000-0000-0000-0000-000000000002';
const member = '10000000-0000-0000-0000-000000000003';
const migration = 'cloudbase/migrations/20260914000005_membership_approval.sql';
let db: PGlite;
let pending: { uid: string; token: string; input: any };
let requestedAdmin: { uid: string; token: string; input: any };
let asset: string;
async function identity(sub = 'anon', role = 'anon', jwtRole = role) {
  await db.exec('reset role');
  await db.query("select set_config('request.jwt.claims',$1,false)", [
    JSON.stringify({ sub, role: jwtRole }),
  ]);
  await db.exec(`set role ${role}`);
}
async function rpc(name: string, args: unknown[] = []) {
  return (
    await db.query<{ result: any }>(
      `select ${name}(${args.map((_, i) => `$${i + 1}`).join(',')}) as result`,
      args,
    )
  ).rows[0].result;
}
async function proof(email: string, score = 100) {
  await identity();
  const exam = await rpc('public.start_exam', [email]);
  expect(exam.questions).toHaveLength(10);
  expect(exam.questions.some((q: any) => 'answer' in q)).toBe(false);
  await identity('anon', 'postgres');
  const answers = (
    await db.query<{ questions: any[] }>(
      'select questions from private.exam_attempts where id=$1',
      [exam.id],
    )
  ).rows[0].questions;
  await identity();
  const result = await rpc('public.submit_exam', [
    exam.id,
    Object.fromEntries(
      answers.map((q, i) => [q.id, i < score / 10 ? q.answer : (q.answer + 1) % 4]),
    ),
  ]);
  await identity('anon', 'postgres');
  return result;
}
async function apply(email: string, requested_role = 'user') {
  const result = await proof(email);
  const input = {
    email,
    token: result.token,
    name: '申请人',
    student_id: 'APPLICANT',
    project: '项目',
    requested_role,
    username: 'hclab_' + createHash('sha256').update(email).digest('hex').slice(0, 40),
    role: 'super_admin',
  };
  const reservation = await rpc('private.claim_registration', [input]);
  await db.query('insert into auth.users(project,sub,username,email) values($1,$2,$3,$4)', [
    env,
    reservation.uid,
    reservation.username,
    email,
  ]);
  await rpc('private.finish_registration', [result.token]);
  return { uid: reservation.uid, token: result.token, input };
}
async function application(uid: string) {
  await identity(uid, 'authenticated');
  const s = await rpc('public.get_snapshot');
  return s.applications?.find((a: any) => a.user_id === uid);
}
beforeAll(async () => {
  db = new PGlite();
  await db.exec(`create role anon; create role authenticated; create schema auth;
    create table auth.users(id bigint generated by default as identity primary key, project varchar(64),sub text,username text,email text,unique(project,sub),unique(project,username));
    create function auth.jwt() returns jsonb language sql stable as $$ select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb $$;
    create function auth.uid() returns text language sql stable as $$ select auth.jwt()->>'sub' $$;
    grant usage on schema auth to anon,authenticated; grant execute on function auth.jwt(),auth.uid() to anon,authenticated;
    create schema storage; create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
    create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,owner_id text);
    alter table storage.objects enable row level security; grant usage on schema storage to authenticated,anon; grant select,insert,delete on storage.objects to authenticated;
  `);
  for (const file of [
    '20260914000000_platform.sql',
    '20260914000001_username_length.sql',
    '20260914000002_rpc_results.sql',
    '20260914000003_rules_update.sql',
    '20260914000004_holiday_question.sql',
  ])
    await db.exec(readFileSync(`cloudbase/migrations/${file}`, 'utf8'));
  for (const [id, role] of [
    [owner, 'admin'],
    [admin, 'admin'],
    [member, 'user'],
  ]) {
    await db.query(
      'insert into public.profiles(id,name,email,student_id,project,role) values($1,$2,$3,$4,$5,$6)',
      [id, '现有成员', `${id}@example.invalid`, 'OLD', '项目', role],
    );
  }
  await db.exec(readFileSync(migration, 'utf8'));
  await db.exec(readFileSync('cloudbase/migrations/20260914000006_equipment_hours.sql', 'utf8'));
  await db.exec(readFileSync('cloudbase/migrations/20260915000000_all_day_equipment.sql', 'utf8'));
  await db.query("update public.profiles set role='super_admin' where id=$1", [owner]);
}, 20000);
afterAll(async () => {
  await db?.close();
});

it('满分申请普通成员和管理员都进入待审核，无自动提权', async () => {
  pending = await apply('pending@example.invalid');
  requestedAdmin = await apply('pending-admin@example.invalid', 'admin');
  for (const [record, requested] of [
    [pending, 'user'],
    [requestedAdmin, 'admin'],
  ] as const) {
    const p = (
      await db.query('select role,membership_status from public.profiles where id=$1', [record.uid])
    ).rows[0];
    expect(p).toEqual({ role: 'user', membership_status: 'pending' });
    const app = await application(record.uid);
    expect(app).toMatchObject({
      requested_role: requested,
      status: 'pending',
      score: 100,
      rules_version: '2026-09-v3',
    });
    await identity('anon', 'postgres');
  }
});
it('保留现有成员准入，只有超级管理员可以看到所有注册申请和通知', async () => {
  for (const id of [member, admin]) {
    await identity(id, 'authenticated');
    const s = await rpc('public.get_snapshot');
    expect(s.profiles.find((p: any) => p.id === id).membership_status).toBe('approved');
    expect(s.applications).toEqual([]);
    expect(s.profiles.some((p: any) => p.id === pending.uid)).toBe(false);
    expect(s.notices.some((n: any) => n.title === '新的注册申请')).toBe(false);
  }
  await identity(owner, 'authenticated');
  const s = await rpc('public.get_snapshot');
  expect(s.applications).toHaveLength(2);
  expect(s.notices.filter((n: any) => n.title === '新的注册申请')).toHaveLength(2);
  expect(await rpc('public.is_admin')).toBe(true);
});
it('超级管理员继承设备管理权限，可作为设备负责人', async () => {
  await identity(owner, 'authenticated');
  asset = (
    await rpc('public.save_equipment_result', [
      {
        name: '测试资产',
        model: '型号',
        category: '工具',
        project: '公共',
        room: '504',
        location: '工作台',
        manager_id: owner,
        status: 'available',
        open_time: '08:00',
        close_time: '22:00',
        weekdays: [0, 1, 2, 3, 4, 5, 6],
        asset_code: 'TEST-MEMBERSHIP',
      },
    ])
  ).id;
  expect(asset).toMatch(/^[a-f0-9-]{36}$/);
});
it('设备保存支持截图中的 00:00—23:59，以及按分钟设置的开放范围', async () => {
  await identity(owner, 'authenticated');
  for (const [open_time, close_time] of [
    ['00:00', '23:59'],
    ['08:10', '17:45'],
  ]) {
    const saved = await rpc('public.save_equipment_result', [
      {
        name: '开放时间回归测试',
        model: 'G1-edu+',
        category: '人形机器人',
        project: '公共设备',
        room: '505',
        location: '指定存放位置',
        manager_id: owner,
        status: 'available',
        open_time,
        close_time,
        weekdays: [0, 1, 2, 3, 4, 5, 6],
        asset_code: randomUUID(),
      },
    ]);
    const snapshot = await rpc('public.get_snapshot');
    expect(snapshot.equipment.find((e: any) => e.id === saved.id)).toMatchObject({
      open_time: `${open_time}:00`,
      close_time: `${close_time}:00`,
      manager_id: owner,
    });
    await expect(
      rpc('public.save_equipment_result', [
        {
          ...snapshot.equipment.find((e: any) => e.id === saved.id),
          open_time: '08:10',
          close_time: '08:40',
        },
      ]),
    ).rejects.toThrow(/equipment_booking_window_check/);
  }
});
it('匿名、普通成员、管理员、待审核账号以及伪造 JWT 角色都不能审核', async () => {
  const app = await application(requestedAdmin.uid);
  for (const [sub, role, jwt] of [
    ['anon', 'anon', 'anon'],
    [member, 'authenticated', 'authenticated'],
    [admin, 'authenticated', 'authenticated'],
    [requestedAdmin.uid, 'authenticated', 'authenticated'],
    [owner, 'authenticated', 'anon'],
  ]) {
    await identity(sub, role, jwt);
    await expect(rpc('public.review_membership', [app.id, 'approve', ''])).rejects.toThrow(
      /permission denied|超级管理员|登录/,
    );
  }
});
it('待审核成员只能读取自己的申请，无法直接写资料、预约、设备或图片', async () => {
  await identity(pending.uid, 'authenticated');
  const s = await rpc('public.get_snapshot');
  expect(s.profiles.map((p: any) => p.id)).toEqual([pending.uid]);
  expect(s.applications.map((p: any) => p.user_id)).toEqual([pending.uid]);
  expect(s.bookings).toEqual([]);
  await expect(
    db.exec("update public.profiles set role='super_admin',membership_status='approved'"),
  ).rejects.toThrow(/permission denied/);
  await expect(db.exec('select * from private.membership_applications')).rejects.toThrow(
    /permission denied/,
  );
  await expect(
    rpc('public.create_booking_result', [
      {
        equipment_id: asset,
        starts_at: '2099-01-04T09:00+08:00',
        ends_at: '2099-01-04T10:00+08:00',
        purpose: '测试',
      },
    ]),
  ).rejects.toThrow(/审核/);
  await expect(rpc('public.save_equipment_result', [{}])).rejects.toThrow(/审核/);
  await expect(
    db.exec("insert into storage.objects(bucket_id,name) values('equipment-images','bad.png')"),
  ).rejects.toThrow(/row-level security/);
  await rpc('public.mark_notices_read');
});
it('重复注册凭证不会改变申请身份、重复通知或绕过审核', async () => {
  await identity('anon', 'postgres');
  await rpc('private.claim_registration', [requestedAdmin.input]);
  await rpc('private.finish_registration', [requestedAdmin.token]);
  await expect(
    rpc('private.claim_registration', [{ ...requestedAdmin.input, requested_role: 'user' }]),
  ).rejects.toThrow(/资料|身份/);
  const s = await application(requestedAdmin.uid);
  expect(s.requested_role).toBe('admin');
  await identity(owner, 'authenticated');
  expect(
    (await rpc('public.get_snapshot')).notices.filter((n: any) => n.title === '新的注册申请'),
  ).toHaveLength(2);
});
it('拒绝非满分或伪造超级管理员身份的注册申请', async () => {
  const failed = await proof('failed@example.invalid', 90);
  expect(failed.passed).toBe(false);
  expect(failed.token).toBeNull();
  await expect(
    rpc('private.claim_registration', [{ ...pending.input, token: randomUUID() }]),
  ).rejects.toThrow(/考试/);
  await expect(
    rpc('private.claim_registration', [{ ...pending.input, requested_role: 'super_admin' }]),
  ).rejects.toThrow(/身份/);
});
it('只有审核通过后才获得所申请的管理员权限，重复审核不会改变已定结果', async () => {
  const app = await application(requestedAdmin.uid);
  await identity(owner, 'authenticated');
  expect(
    await rpc('public.review_membership', [app.id, 'approve', '已核实实验室成员身份']),
  ).toMatchObject({ status: 'approved' });
  expect(await rpc('public.review_membership', [app.id, 'approve', '重试'])).toMatchObject({
    status: 'approved',
  });
  await expect(rpc('public.review_membership', [app.id, 'reject', '改为拒绝'])).rejects.toThrow(
    /已审核/,
  );
  await identity(requestedAdmin.uid, 'authenticated');
  expect(await rpc('public.is_admin')).toBe(true);
  const s = await rpc('public.get_snapshot');
  expect(s.profiles.find((p: any) => p.id === requestedAdmin.uid)).toMatchObject({
    role: 'admin',
    membership_status: 'approved',
  });
  expect(s.notices.filter((n: any) => n.title === '注册申请已通过')).toHaveLength(1);
});
it('拒绝申请须说明原因，拒绝后保持无准入权限', async () => {
  const app = await application(pending.uid);
  await identity(owner, 'authenticated');
  await expect(rpc('public.review_membership', [app.id, 'reject', ''])).rejects.toThrow(/原因/);
  await rpc('public.review_membership', [app.id, 'reject', '未能核实成员身份']);
  expect(await application(pending.uid)).toMatchObject({
    status: 'rejected',
    review_note: '未能核实成员身份',
  });
  await expect(
    rpc('public.create_booking_result', [
      {
        equipment_id: asset,
        starts_at: '2099-01-04T11:00+08:00',
        ends_at: '2099-01-04T12:00+08:00',
        purpose: '测试',
      },
    ]),
  ).rejects.toThrow(/审核/);
});
it('普通成员申请获批后只得到普通成员权限，越权修改角色仍被拒绝', async () => {
  const record = await apply('ordinary@example.invalid');
  const app = await application(record.uid);
  await identity(owner, 'authenticated');
  await rpc('public.review_membership', [app.id, 'approve', '']);
  await identity(record.uid, 'authenticated');
  expect(await rpc('public.is_admin')).toBe(false);
  expect(
    (
      await rpc('public.create_booking_result', [
        {
          equipment_id: asset,
          starts_at: '2099-01-04T13:00+08:00',
          ends_at: '2099-01-04T14:00+08:00',
          purpose: '测试',
        },
      ])
    ).id,
  ).toBeTruthy();
  await expect(rpc('public.review_membership', [app.id, 'approve', ''])).rejects.toThrow(
    /超级管理员/,
  );
});

it('全天设备可预约至次日零点，审批和占用检查仍生效', async () => {
  await identity(owner, 'authenticated');
  const saved = await rpc('public.save_equipment_result', [
    {
      name: '全天设备',
      model: '测试型号',
      category: '工具',
      project: '公共设备',
      room: '505',
      location: '指定位置',
      manager_id: owner,
      status: 'available',
      open_time: '00:00',
      close_time: '24:00',
      weekdays: [0, 1, 2, 3, 4, 5, 6],
      asset_code: randomUUID(),
    },
  ]);
  const e = (await rpc('public.get_snapshot')).equipment.find((e: any) => e.id === saved.id);
  expect(e.close_time).toBe('24:00:00');
  const input = {
    equipment_id: saved.id,
    starts_at: '2099-01-05T23:30+08:00',
    ends_at: '2099-01-06T00:00+08:00',
    purpose: '全天边界测试',
  };
  await identity(member, 'authenticated');
  const booking = await rpc('public.create_booking_result', [input]);
  await expect(rpc('public.create_booking_result', [input])).rejects.toThrow(/已有预约/);
  for (const ends_at of ['2099-01-06T00:30+08:00', '2099-01-07T00:00+08:00'])
    await expect(rpc('public.create_booking_result', [{ ...input, ends_at }])).rejects.toThrow(
      /跨日/,
    );
  await identity(owner, 'authenticated');
  await rpc('public.booking_action', [booking.id, 'approve', '']);
  await identity(member, 'authenticated');
  const next = await rpc('public.create_booking_result', [
    {
      ...input,
      starts_at: '2099-01-06T00:00+08:00',
      ends_at: '2099-01-06T00:30+08:00',
      parent_id: booking.id,
    },
  ]);
  expect(next.id).toBeTruthy();
  await identity(owner, 'authenticated');
  await rpc('public.save_equipment_result', [{ ...e, close_time: '23:59' }]);
  await expect(
    rpc('public.create_booking_result', [
      { ...input, starts_at: '2099-01-07T23:30+08:00', ends_at: '2099-01-08T00:00+08:00' },
    ]),
  ).rejects.toThrow(/开放时段/);
  await rpc('public.save_equipment_result', [{ ...e, weekdays: [1] }]);
  await expect(
    rpc('public.create_booking_result', [
      { ...input, starts_at: '2099-01-06T12:00+08:00', ends_at: '2099-01-06T12:30+08:00' },
    ]),
  ).rejects.toThrow(/开放日/);
  const fullDay = await rpc('public.create_booking_result', [
    { ...input, starts_at: '2099-01-12T00:00+08:00', ends_at: '2099-01-13T00:00+08:00' },
  ]);
  expect(fullDay.id).toBeTruthy();
});
