import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { PGlite } from '@electric-sql/pglite';
import { readFileSync, readdirSync } from 'node:fs';
import { randomUUID } from 'node:crypto';

describe.each(['cloudbase', 'supabase'])('%s 多图与归还凭证', (backend) => {
  let db: PGlite;
  const admin = randomUUID(),
    member = randomUUID(),
    other = randomUUID();
  async function identity(uid: string | null, role = 'authenticated') {
    await db.exec('reset role');
    await db.query("select set_config('request.jwt.claims',$1,false)", [
      JSON.stringify({ sub: uid, role }),
    ]);
    await db.exec(`set role ${role}`);
  }
  async function rpc(name: string, args: unknown[] = []) {
    return (
      await db.query<{ value: any }>(
        `select public.${name}(${args.map((_, i) => '$' + (i + 1)).join(',')}) as value`,
        args,
      )
    ).rows[0].value;
  }
  async function asset(images?: string[]) {
    await identity(admin);
    const input = {
      name: '照片验收设备',
      model: 'TEST',
      category: '工具',
      project: '测试',
      room: '505',
      location: '指定位置',
      manager_id: admin,
      status: 'available',
      open_time: '00:00',
      close_time: '24:00',
      weekdays: [0, 1, 2, 3, 4, 5, 6],
      asset_code: randomUUID(),
      image_urls: images,
      image_url: '',
    };
    const id = await rpc('save_equipment', [input]);
    return { ...input, id };
  }
  async function inUse() {
    const e = await asset();
    await identity(null, 'postgres');
    const b = (
      await db.query<{ id: string }>(
        "insert into public.bookings(equipment_id,user_id,user_name,starts_at,ends_at,purpose,status) values($1,$2,'照片测试成员',now()-interval '1 hour',now()+interval '1 hour','照片验收','in_use') returning id",
        [e.id, member],
      )
    ).rows[0];
    await identity(member);
    return b.id;
  }
  beforeAll(async () => {
    db = new PGlite();
    const type = backend === 'cloudbase' ? 'text' : 'uuid';
    await db.exec(`create role anon;create role authenticated;create schema auth;
      create table auth.users(id ${backend === 'cloudbase' ? 'bigint generated by default as identity' : 'uuid'} primary key,project text,sub text,username text,email text,raw_user_meta_data jsonb default '{}');
      create function auth.jwt() returns jsonb language sql stable as $$select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$;
      create function auth.uid() returns ${type} language sql stable as $$select nullif(auth.jwt()->>'sub','')::${type}$$;
      grant usage on schema auth to anon,authenticated;grant execute on function auth.jwt(),auth.uid() to anon,authenticated;
      create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
      create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,owner_id text);
      alter table storage.objects enable row level security;grant usage on schema storage to anon,authenticated;
      grant select,insert,update,delete on storage.objects to anon,authenticated;`);
    const dir = backend + '/migrations';
    for (const file of readdirSync(dir)
      .filter((f) => f.endsWith('.sql'))
      .sort())
      await db.exec(readFileSync(dir + '/' + file, 'utf8'));
    if (backend === 'supabase') {
      await db.exec('alter table auth.users disable trigger all');
      for (const id of [admin, member, other])
        await db.query('insert into auth.users(id,email) values($1,$2)', [
          id,
          `${id}@example.invalid`,
        ]);
      await db.exec('alter table auth.users enable trigger all');
    }
    for (const id of [admin, member, other])
      await db.query(
        "insert into public.profiles(id,name,email,student_id,role,membership_status) values($1,'照片测试成员',$2,'TEST',$3,'approved')",
        [id, `${id}@example.invalid`, id === admin ? 'super_admin' : 'user'],
      );
  }, 30000);
  afterAll(async () => {
    await db?.close();
  });

  it('保存多图顺序并使用第一张封面，旧客户端编辑不会丢失其他图片', async () => {
    const urls = ['https://images.example/first.jpg', 'https://images.example/second.png'];
    const e = await asset(urls);
    let saved = (await rpc('get_snapshot')).equipment.find((x: any) => x.id === e.id);
    expect(saved.image_urls).toEqual(urls);
    expect(saved.image_url).toBe(urls[0]);
    const { image_urls: _, ...legacy } = saved;
    await rpc('save_equipment', [{ ...legacy, name: '旧版编辑' }]);
    saved = (await rpc('get_snapshot')).equipment.find((x: any) => x.id === e.id);
    expect(saved.image_urls).toEqual(urls);
    await rpc('save_equipment', [{ ...saved, image_urls: [urls[1]] }]);
    expect((await rpc('get_snapshot')).equipment.find((x: any) => x.id === e.id).image_url).toBe(
      urls[1],
    );
    await expect(
      rpc('save_equipment', [{ ...saved, image_urls: ['javascript:alert(1)'] }]),
    ).rejects.toThrow(/HTTPS|图片/);
  });
  it('没有照片的旧版归还请求被拒绝，设备仍处于使用中', async () => {
    const id = await inUse();
    await expect(
      rpc('booking_action', [id, 'return', '设备正常，放回505指定位置']),
    ).rejects.toThrow(/照片/);
    expect((await rpc('get_snapshot')).bookings.find((x: any) => x.id === id).status).toBe(
      'in_use',
    );
  });
  it('必须使用实际上传且属于本预约的照片，归还后可核对且禁止覆盖和删除', async () => {
    const id = await inUse(),
      path = `${id}/${randomUUID()}.jpg`;
    await expect(rpc('booking_action', [id, 'return', '正常', path])).rejects.toThrow(/照片/);
    await identity(other);
    await expect(
      db.query("insert into storage.objects(bucket_id,name) values('return-photos',$1)", [path]),
    ).rejects.toThrow(/row.level|permission/);
    await identity(member);
    await db.query(
      "insert into storage.objects(bucket_id,name,owner_id) values('return-photos',$1,$2)",
      [path, member],
    );
    await expect(
      rpc('booking_action', [id, 'return', '正常', `${randomUUID()}/${randomUUID()}.jpg`]),
    ).rejects.toThrow(/照片/);
    await rpc('booking_action', [id, 'return', '外壳存在故障，已备注通知管理员', path]);
    const saved = (await rpc('get_snapshot')).bookings.find((x: any) => x.id === id);
    expect(saved).toMatchObject({
      status: 'returned',
      return_photo_path: path,
      return_note: '外壳存在故障，已备注通知管理员',
    });
    expect(saved.returned_at).toBeTruthy();
    await db.query("delete from storage.objects where bucket_id='return-photos' and name=$1", [
      path,
    ]);
    await db.query(
      "update storage.objects set name='changed.jpg' where bucket_id='return-photos' and name=$1",
      [path],
    );
    expect(
      (
        await db.query(
          "select name from storage.objects where bucket_id='return-photos' and name=$1",
          [path],
        )
      ).rows,
    ).toHaveLength(1);
    await identity(other);
    expect(
      (await db.query("select name from storage.objects where bucket_id='return-photos'")).rows,
    ).toHaveLength(0);
    await expect(
      db.query("insert into storage.objects(bucket_id,name) values('return-photos',$1)", [
        `${id}/${randomUUID()}.jpg`,
      ]),
    ).rejects.toThrow(/row.level|permission/);
    await identity(null, 'anon');
    expect(
      (await db.query("select name from storage.objects where bucket_id='return-photos'")).rows,
    ).toHaveLength(0);
    await identity(admin);
    expect(
      (
        await db.query(
          "select name from storage.objects where bucket_id='return-photos' and name=$1",
          [path],
        )
      ).rows,
    ).toHaveLength(1);
  });
});
